using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Arklens.Generators;

public static partial class SourceOf
{
    public static SourceText AlidLookup(IEnumerable<ITypeSymbol> types)
        => SourceText.From(@$"// <auto-generated/>
#nullable enable
using System.Collections.Frozen;
using System.Collections.Generic;
using Arklens.Core;

namespace Arklens.Alids;

partial interface IAlidEntity
{{
    private static partial IEnumerable<IAlidEntity> GetEntities() =>
    [
{string.Join(",\n", types.Select(GetPropertyText))}
    ];
}}", Encoding.UTF8);

    private static string GetPropertyText(ITypeSymbol type) => $"\t\t{GetProperty(type)}";
    private static string GetProperty(ITypeSymbol type) =>
        type.Interfaces.Any(i => i.Name == "ISingleton")
            ? $"{type.ContainingNamespace.ToDisplayString()}.{type.Name}.Instance"
            : $"..{type.ContainingNamespace.ToDisplayString()}.{type.Name}.AllValues";
}