using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Arklens.Generators;

public static partial class SourceOf
{
    public static SourceText AlidGroups(IEnumerable<ITypeSymbol> types)
        => SourceText.From(@$"// <auto-generated/>
#nullable enable
using System.Collections.Frozen;
using System.Collections.Generic;
using Arklens.Core;

namespace Arklens.Alids;

public static partial class AlidGroups
{{
    private static partial IEnumerable<AlidGroup> GetGroups() =>
    [
{string.Join(",\n", types.Select(x => $"\t\tnew {x.ContainingType.ToDisplayString()}.{x.Name}()"))}
    ];
}}
", Encoding.UTF8);
}