using System;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Arklens.Generators;

public partial class SourceOf
{
    public static SourceText GenerateEnumerationAttribute { get; } = SourceText.From(@$"// <auto-generated/>
using System;

namespace {typeof(SourceOf).Namespace};

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public class {nameof(GenerateEnumerationAttribute)} : {nameof(Attribute)};
", Encoding.UTF8);
}